services:
  app:
    container_name: plagiarism-detection
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    working_dir: /app
    volumes:
      - type: bind
        source: .
        target: /app
      - type: bind
        source: ./data/raw
        target: /app/data/raw
        read_only: true
    stdin_open: true
    tty: true
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"
